### ISSUE TITLE
Issues getting this to run

### ISSUE THREAD

**Issue by encukou** [pyvec/arca#5]
These might be for other repos, but they shouldn't be forgotten:

* [x] The `.arca` directory should be created if it doesn't exist
* [x] Redis should be optional

**Comment by mikicz** [comment]
1) fixed in https://github.com/mikicz/naucse.python.cz/commit/2130b781d775cbb75bec497025ae3c97f68420b3
2) redis was already optional, it's only required when redis backend is configured for dogpile cache, added bit more handling here: https://github.com/mikicz/arca/commit/d39e3207979606d9934de3f089f6b3ba25b27f18
